name: Dagger Review

on:
  pull_request:
    types: [labeled]

jobs:
  review:
    if: github.event.label.name == 'review'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install uv
      - name: Run Dagger review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          uv pip install -r requirements.txt
          python3 review.py
